### ISSUE TITLE
Is this project still working?

### ISSUE THREAD

**Issue by briceparent** [BenediktSeidl/fzpzf#1]
Sorry to wake a 5 year old project up, but before taking a deeper look into it, I'd like to know if Fritzing's constant developing have made this script obsolete, or if it should still work (or if it is still used).

Thanks !

**Comment by BenediktSeidl** [comment]
it is not used anymore. but it [seems](http://fritzing.org/learning/tutorials/creating-custom-parts/) like there is still a lot of manual work involved when creating new parts.
 
not sure if the graphics convention for fritzing changed a lot in the last five years.

if you want to use it and run into any issues, let me know, i will try my best to fix them.

**Comment by briceparent** [comment]
Thanks for the info, I'll take a deeper look into it soon.

I'll come back to you if I need it, thanks again.
